[tool.poetry]
name = "maya-frontend"
version = "3.0.0"
description = "Discord Frontend"
authors = ["Cameron Kauffman <clk9699@gmail.com>"]
license = "CC BY-NC-ND 4.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
py-cord = {extras = ["speed"], version = "^2.6.1"}
dotenv = "^0.9.9"
colorlog = "^6.9.0"
requests = "^2.32.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
